import type { Theme } from "theme-ui"

export const jobFinderTheme: Theme = {
  space: [0, "0.2rem", "0.4rem", "0.75rem", "1rem", "1.5rem", "2rem", "2.75rem", "3.5rem"],
  fontSizes: ["0.7rem", "0.75rem", "0.8125rem", "0.875rem", "0.9375rem", "1.0625rem", "1.25rem", "1.5rem"],
  fonts: {
    body: 'Inter, system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif',
    heading: 'Space Grotesk, Inter, system-ui, -apple-system, "Segoe UI", sans-serif',
    mono: '"JetBrains Mono", "IBM Plex Mono", Menlo, monospace',
  },
  fontWeights: {
    body: 400,
    medium: 500,
    heading: 600,
    bold: 700,
  },
  lineHeights: {
    body: 1.5,
    heading: 1.25,
    dense: 1.35,
  },
  colors: {
    background: "#050912",
    backgroundSunken: "#04070d",
    surface: "#0b1220",
    surfaceRaised: "#101a2c",
    surfaceMuted: "rgba(15, 23, 42, 0.66)",
    surfaceHover: "rgba(148, 163, 184, 0.08)",
    border: "#1e2a3f",
    divider: "#1e2a3f",
    borderMuted: "rgba(148, 163, 184, 0.2)",
    borderStrong: "#2f3d57",
    text: "#e2e8f0",
    textMuted: "#94a3b8",
    heading: "#f8fafc",
    primary: "#38bdf8",
    primaryHover: "#0ea5e9",
    primarySoft: "rgba(56, 189, 248, 0.14)",
    success: "#4ade80",
    successSoft: "rgba(74, 222, 128, 0.14)",
    warning: "#facc15",
    warningSoft: "rgba(250, 204, 21, 0.14)",
    danger: "#f87171",
    dangerSoft: "rgba(248, 113, 113, 0.16)",
    info: "#818cf8",
    infoSoft: "rgba(129, 140, 248, 0.16)",
    signalStrong: "#22d3ee",
    signalFair: "#fbbf24",
    signalLow: "#f97316",
    muted: "rgba(15, 23, 42, 0.9)",
    highlight: "rgba(56, 189, 248, 0.12)",
  },
  radii: {
    xs: "4px",
    sm: "6px",
    md: "10px",
    lg: "16px",
    pill: "999px",
  },
  shadows: {
    card: "0px 24px 48px rgba(2, 6, 23, 0.45)",
    inset: "inset 0 1px 0 rgba(148, 163, 184, 0.08)",
    focus: "0 0 0 1px rgba(56, 189, 248, 0.45)",
  },
  cards: {
    primary: {
      bg: "surface",
      border: "1px solid",
      borderColor: "border",
      borderRadius: "lg",
      boxShadow: "card",
      position: "relative",
      "&::after": {
        content: "''",
        position: "absolute",
        inset: 0,
        borderRadius: "inherit",
        pointerEvents: "none",
        boxShadow: "inset 0 1px 0 rgba(255, 255, 255, 0.04)",
      },
    },
    metric: {
      variant: "cards.primary",
      display: "flex",
      flexDirection: "column",
      gap: 2,
      bg: "surfaceRaised",
      borderColor: "borderMuted",
      boxShadow: "inset",
    },
    elevated: {
      variant: "cards.primary",
      bg: "surfaceRaised",
    },
  },
  buttons: {
    primary: {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      gap: 2,
      bg: "primary",
      color: "background",
      fontSize: 1,
      fontWeight: "medium",
      px: 3,
      py: 2,
      borderRadius: "pill",
      border: "1px solid",
      borderColor: "primary",
      textTransform: "uppercase",
      letterSpacing: "0.05em",
      transition: "all 0.18s ease-in-out",
      cursor: "pointer",
      "&:hover": {
        bg: "primaryHover",
        borderColor: "primaryHover",
        transform: "translateY(-1px)",
      },
      "&:focus-visible": {
        outline: "none",
        boxShadow: "focus",
      },
      "&:disabled": {
        opacity: 0.45,
        cursor: "not-allowed",
        transform: "none",
      },
    },
    secondary: {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      gap: 2,
      bg: "surfaceRaised",
      color: "text",
      fontSize: 1,
      fontWeight: "medium",
      px: 3,
      py: 2,
      borderRadius: "pill",
      border: "1px solid",
      borderColor: "border",
      transition: "all 0.18s ease-in-out",
      cursor: "pointer",
      "&:hover": {
        bg: "surface",
        borderColor: "primary",
        color: "primary",
      },
      "&:focus-visible": {
        outline: "none",
        boxShadow: "focus",
      },
      "&:disabled": {
        opacity: 0.5,
        cursor: "not-allowed",
      },
    },
    ghost: {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      gap: 2,
      bg: "transparent",
      color: "text",
      fontSize: 1,
      fontWeight: "medium",
      px: 2,
      py: 1,
      borderRadius: "pill",
      border: "1px solid transparent",
      transition: "all 0.18s ease-in-out",
      cursor: "pointer",
      "&:hover": {
        bg: "surfaceHover",
        borderColor: "borderMuted",
      },
      "&:focus-visible": {
        outline: "none",
        boxShadow: "focus",
      },
    },
    chip: {
      display: "inline-flex",
      alignItems: "center",
      justifyContent: "center",
      gap: 2,
      bg: "surfaceRaised",
      color: "text",
      fontSize: 0,
      fontWeight: "medium",
      px: 2,
      py: 1,
      borderRadius: "pill",
      border: "1px solid",
      borderColor: "borderMuted",
      textTransform: "uppercase",
      letterSpacing: "0.08em",
      transition: "all 0.16s ease",
      cursor: "pointer",
      "&:hover": {
        bg: "surface",
        borderColor: "primary",
        color: "primary",
      },
      "&[data-active=true]": {
        bg: "primarySoft",
        borderColor: "primary",
        color: "primary",
      },
    },
  },
  badges: {
    success: {
      bg: "successSoft",
      color: "success",
      borderRadius: "pill",
      px: 2,
      py: "2px",
      fontSize: 0,
      fontWeight: "medium",
      letterSpacing: "0.04em",
    },
    danger: {
      bg: "dangerSoft",
      color: "danger",
      borderRadius: "pill",
      px: 2,
      py: "2px",
      fontSize: 0,
      fontWeight: "medium",
      letterSpacing: "0.04em",
    },
    warning: {
      bg: "warningSoft",
      color: "warning",
      borderRadius: "pill",
      px: 2,
      py: "2px",
      fontSize: 0,
      fontWeight: "medium",
      letterSpacing: "0.04em",
    },
    info: {
      bg: "infoSoft",
      color: "info",
      borderRadius: "pill",
      px: 2,
      py: "2px",
      fontSize: 0,
      fontWeight: "medium",
      letterSpacing: "0.04em",
    },
    muted: {
      bg: "surfaceHover",
      color: "textMuted",
      borderRadius: "pill",
      px: 2,
      py: "2px",
      fontSize: 0,
      fontWeight: "medium",
      letterSpacing: "0.04em",
    },
  },
  forms: {
    label: {
      fontSize: 0,
      fontWeight: "medium",
      textTransform: "uppercase",
      color: "textMuted",
      letterSpacing: "0.08em",
      mb: 2,
    },
    input: {
      bg: "surfaceRaised",
      color: "text",
      borderRadius: "sm",
      border: "1px solid",
      borderColor: "border",
      px: 3,
      py: 2,
      fontSize: 1,
      fontFamily: "body",
      transition: "all 0.18s ease",
      "&:focus": {
        outline: "none",
        borderColor: "primary",
        boxShadow: "0 0 0 1px rgba(56, 189, 248, 0.4)",
        bg: "surface",
      },
      "&::placeholder": {
        color: "textMuted",
      },
    },
    select: {
      variant: "forms.input",
      pr: 5,
      appearance: "none",
      backgroundImage:
        "linear-gradient(45deg, transparent 50%, currentColor 50%), linear-gradient(135deg, currentColor 50%, transparent 50%)",
      backgroundPosition: "calc(100% - 16px) calc(50% - 4px), calc(100% - 11px) calc(50% - 4px)",
      backgroundSize: "6px 6px, 6px 6px",
      backgroundRepeat: "no-repeat",
    },
    textarea: {
      variant: "forms.input",
      minHeight: "140px",
    },
    checkbox: {
      width: "16px",
      height: "16px",
      borderRadius: "4px",
      border: "1px solid",
      borderColor: "border",
      bg: "surface",
      position: "relative",
      cursor: "pointer",
      appearance: "none",
      "&:checked": {
        bg: "primary",
        borderColor: "primary",
      },
      "&:focus": {
        outline: "none",
        boxShadow: "focus",
      },
      "&:checked::after": {
        content: "\u2713",
        position: "absolute",
        top: "-2px",
        left: "2px",
        fontSize: "14px",
        color: "background",
      },
    },
  },
  textStyles: {
    label: {
      textTransform: "uppercase",
      letterSpacing: "0.08em",
      fontSize: 0,
      fontWeight: "medium",
      color: "textMuted",
    },
    helper: {
      fontSize: 0,
      color: "textMuted",
    },
  },
}
