name: Deploy to Production

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    name: Build and Deploy (production)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Cache Gatsby build
        uses: actions/cache@v4
        with:
          path: |
            .cache
            public
          key: gatsby-prod-${{ runner.os }}-${{ hashFiles('gatsby-config.ts', 'package-lock.json') }}-${{ github.sha }}
          restore-keys: |
            gatsby-prod-${{ runner.os }}-${{ hashFiles('gatsby-config.ts', 'package-lock.json') }}-
            gatsby-prod-${{ runner.os }}-

      - name: Install dependencies
        run: npm ci --legacy-peer-deps --prefer-offline --no-audit --no-fund

      - name: Build
        run: npm run build
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"

      - name: Deploy to Firebase Hosting (production)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: static-sites-257923
          channelId: live
          target: production
