name: Deploy to Production

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    name: Build and Deploy (production)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 make g++

      - name: Install dependencies
        run: npm ci --include=optional --legacy-peer-deps

      - name: Install and verify @parcel/watcher
        run: |
          echo "Installing @parcel/watcher with prebuilds..."
          npm install --no-save @parcel/watcher@2.5.1

          echo "Rebuilding native module..."
          npm rebuild @parcel/watcher --verbose

          echo "Verifying installation..."
          if [ ! -d "node_modules/@parcel/watcher" ]; then
            echo "ERROR: @parcel/watcher not installed"
            exit 1
          fi

          echo "Directory structure:"
          ls -la node_modules/@parcel/watcher/

          echo "Checking for native binding..."
          if [ -f "node_modules/@parcel/watcher/watcher.node" ]; then
            echo "✓ Native binding found: watcher.node"
            file node_modules/@parcel/watcher/watcher.node
          else
            echo "⚠ Native binding not found"
          fi

          echo "Checking prebuilds..."
          if [ -d "node_modules/@parcel/watcher/prebuilds" ]; then
            ls -la node_modules/@parcel/watcher/prebuilds/
          else
            echo "No prebuilds directory"
          fi

          echo "Testing require..."
          node -e "require('@parcel/watcher')" && echo "✓ Module loads successfully" || echo "✗ Module failed to load"

      - name: Clean Gatsby cache
        run: npm run clean

      - name: Build
        run: npm run build
        env:
          NODE_OPTIONS: "--max-old-space-size=8192"

      - name: Deploy to Firebase Hosting (production)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: static-sites-257923
          channelId: live
          target: production
