name: Deploy to Staging

on:
  push:
    branches:
      - staging

permissions:
  contents: read

jobs:
  deploy:
    name: Build and Deploy (staging)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci --include=optional --legacy-peer-deps

      - name: Verify @parcel/watcher installation
        run: |
          if [ ! -d "node_modules/@parcel/watcher" ]; then
            echo "ERROR: @parcel/watcher not installed"
            exit 1
          fi
          echo "@parcel/watcher is installed"

      - name: Clean Gatsby cache
        run: npm run clean

      - name: Set build environment
        run: |
          echo "GATSBY_BUILD_ENVIRONMENT=staging" >> $GITHUB_ENV
          echo "GATSBY_BUILD_TIMESTAMP=$(date -u +%Y-%m-%dT%H:%M:%SZ)" >> $GITHUB_ENV
          echo "GATSBY_BUILD_COMMIT=${GITHUB_SHA}" >> $GITHUB_ENV

      - name: Build
        run: npm run build
        env:
          NODE_OPTIONS: "--max-old-space-size=6144"
          GATSBY_EXPERIMENTAL_FAST_DEV: "true"

      - name: Deploy to Firebase Hosting (staging)
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
          projectId: static-sites-257923
          channelId: live
          target: staging
