name: Deploy Contact Form Function

on:
  push:
    branches:
      - main
      - staging
    paths:
      - "functions/**"
  pull_request:
    branches:
      - main
      - staging
    paths:
      - "functions/**"

env:
  GCP_PROJECT_ID: static-sites-257923
  FUNCTION_NAME: contact-form
  FUNCTION_REGION: us-central1

jobs:
  test:
    name: Test Function
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint
        working-directory: functions

      - name: Run tests
        run: npm test
        working-directory: functions

      - name: Build TypeScript
        run: npm run build
        working-directory: functions

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/staging' && github.event_name == 'push'
    environment:
      name: staging
      url: https://us-central1-static-sites-257923.cloudfunctions.net/contact-form

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build function
        run: npm run build
        working-directory: functions

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Functions (Staging)
        run: |
          gcloud functions deploy ${{ env.FUNCTION_NAME }}-staging \
            --gen2 \
            --runtime=nodejs20 \
            --region=${{ env.FUNCTION_REGION }} \
            --source=functions \
            --entry-point=handleContactForm \
            --trigger-http \
            --allow-unauthenticated \
            --memory=256Mi \
            --timeout=60s \
            --max-instances=10 \
            --set-env-vars="NODE_ENV=staging,ENVIRONMENT=staging" \
            --set-secrets="MAILGUN_API_KEY=mailgun-api-key:latest,MAILGUN_DOMAIN=mailgun-domain:latest,FROM_EMAIL=from-email:latest,TO_EMAIL=to-email:latest,REPLY_TO_EMAIL=reply-to-email:latest" \
            --quiet

      - name: Get function URL
        id: get-url
        run: |
          URL=$(gcloud functions describe ${{ env.FUNCTION_NAME }}-staging \
            --region=${{ env.FUNCTION_REGION }} \
            --format="value(serviceConfig.uri)")
          echo "function-url=$URL" >> $GITHUB_OUTPUT

      - name: Test deployed function
        run: |
          curl -X POST "${{ steps.get-url.outputs.function-url }}" \
            -H "Content-Type: application/json" \
            -d '{"name":"Test","email":"test@example.com","message":"Integration test from CI/CD"}' \
            --fail-with-body

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    environment:
      name: production
      url: https://us-central1-static-sites-257923.cloudfunctions.net/contact-form

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build function
        run: npm run build
        working-directory: functions

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Functions (Production)
        run: |
          gcloud functions deploy ${{ env.FUNCTION_NAME }} \
            --gen2 \
            --runtime=nodejs20 \
            --region=${{ env.FUNCTION_REGION }} \
            --source=functions \
            --entry-point=handleContactForm \
            --trigger-http \
            --allow-unauthenticated \
            --memory=512Mi \
            --timeout=60s \
            --max-instances=50 \
            --set-env-vars="NODE_ENV=production,ENVIRONMENT=production" \
            --set-secrets="MAILGUN_API_KEY=mailgun-api-key:latest,MAILGUN_DOMAIN=mailgun-domain:latest,FROM_EMAIL=from-email:latest,TO_EMAIL=to-email:latest,REPLY_TO_EMAIL=reply-to-email:latest" \
            --quiet

      - name: Get function URL
        id: get-url
        run: |
          URL=$(gcloud functions describe ${{ env.FUNCTION_NAME }} \
            --region=${{ env.FUNCTION_REGION }} \
            --format="value(serviceConfig.uri)")
          echo "function-url=$URL" >> $GITHUB_OUTPUT

      - name: Test deployed function
        run: |
          curl -X POST "${{ steps.get-url.outputs.function-url }}" \
            -H "Content-Type: application/json" \
            -d '{"name":"Test","email":"test@example.com","message":"Integration test from CI/CD"}' \
            --fail-with-body
