name: Bundle Size Check

on:
  pull_request:
    branches:
      - main
      - staging
    paths:
      - 'web/**'
      - 'package-lock.json'

permissions:
  contents: read
  pull-requests: write

jobs:
  size:
    name: Check bundle size
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Gatsby site
        run: npm run build -w web
        env:
          NODE_ENV: production
          GATSBY_ENABLE_ANALYTICS: false

      - name: Check bundle size
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: web
          build_script: echo "Already built"
